owner: UmmItKin
repo: Upptime

sites:
  - name: Links
    url: https://links.ummit.dev
  - name: Blog
    url: https://blog.ummit.dev

status-website:
  cname: status.ummit.dev
  # baseUrl: /Upptime
  logoUrl: https://avatars.githubusercontent.com/u/128139875?v=4
  name: UmmIt - Status page
  introTitle: "**UmmIt Status** ALL Server Status."
  introMessage: I Love Open-source.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  favicon: https://avatars.githubusercontent.com/u/128139875?v=4
